version: '3.8'

services:
  db:
    container_name: psql
    restart: always
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=codeleap
      - POSTGRES_USER=skapskap
      - POSTGRES_PASSWORD=DMKO0ZI9a*^N
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  api:
    build: .
    command: python manage.py runserver  0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: